# Generated by Django 4.0.5 on 2022-08-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='Minsk', max_length=30),
        ),
    ]
